import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navBar";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "David Adam's portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* For inline script information: https://nextjs.org/docs/messages/inline-script-id */}
        <Script id="TrulyBadgeScript">
          {`(function () { 
          var script = document.createElement('script'); 

          script.src = 'https://kmgu6d1qxk.execute-api.us-east-2.amazonaws.com/test/api/tlv1?siteId=67049c5c-d069-4669-ab2b-2c1ba25573f3'; 
          script.async = true; 

          var entry = document.getElementsByTagName('script')[0]; 
          entry.parentNode.insertBefore(script, entry); 
          })();`}
          {/*Prod Badges*/}
          {/* {`(function () { 
          var script = document.createElement('script'); 
          
          script.src = 'https://badge.trulylegit.com/api/tlv1?siteId=cb9987fb-e274-42a5-b4e1-8bb8b3236883'; 
          script.async = true; 
          
          var entry = document.getElementsByTagName('script')[0]; 
          entry.parentNode.insertBefore(script, entry); 
          })();`} */}
          {/*QA 24hr notification Badges*/}
          {/* {`(function () {
          var script = document.createElement('script');

          script.src = 'https://kmgu6d1qxk.execute-api.us-east-2.amazonaws.com/test/api/tlv1?siteId=0685c3d6-24eb-4d28-b323-09a4f0d46cf1';
          script.async = true;

          var entry = document.getElementsByTagName('script')[0];
          entry.parentNode.insertBefore(script, entry);
          })();`} */}
          {/*Dev Badges*/}
          {/* {`(function () { 
          var script = document.createElement('script'); 
          
          script.src = 'https://tmmdkra163.execute-api.us-east-2.amazonaws.com/test/api/tlv1?siteId=5e2d9c59-3aef-498f-8436-5134a8762509'; 
          script.async = true; 
          
          var entry = document.getElementsByTagName('script')[0]; 
          entry.parentNode.insertBefore(script, entry); })();`} */}
        </Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
